# Generated by Django 3.1.4 on 2023-12-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0061_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='partenaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
