# Generated by Django 3.1.4 on 2023-12-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_partenaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaires',
            name='logo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='partenaires',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
