# Generated by Django 3.1.4 on 2023-12-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0063_auto_20231223_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaires',
            name='partner_id',
            field=models.IntegerField(default=0),
        ),
    ]
