# Generated by Django 3.1.4 on 2023-12-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_partenaires_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaires',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
