# Generated by Django 3.1.4 on 2023-12-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0065_partenaires_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_id', models.IntegerField(default=0)),
                ('formation_name', models.CharField(default='', max_length=100)),
                ('formation_descr', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
