# Generated by Django 3.1.4 on 2023-12-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0068_auto_20231230_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='bientot',
            name='prog_img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
