# Generated by Django 3.1.4 on 2023-12-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0069_bientot_prog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='collabo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(default='', max_length=100)),
                ('date_birth', models.DateField(default='')),
                ('picture', models.CharField(default='', max_length=100)),
                ('date_member', models.DateField(default='')),
            ],
        ),
    ]
