# Generated by Django 3.1.4 on 2023-12-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0070_collabo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabo',
            name='post',
            field=models.CharField(default='', max_length=100),
        ),
    ]
