# Generated by Django 3.1.4 on 2023-12-30 13:26

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0072_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date.today),  # Utilisation de la date actuelle
    preserve_default=True,
        ),
    ]
