# Generated by Django 3.1.4 on 2023-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0074_auto_20231230_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
