# Generated by Django 3.1.4 on 2023-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0075_auto_20231230_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
