# Generated by Django 3.1.4 on 2023-12-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0077_auto_20231230_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='dateMessage',
        ),
    ]
