# Generated by Django 3.1.4 on 2023-12-30 13:46

from django.db import migrations, models

def set_default_date(apps, schema_editor):
    Message = apps.get_model('posts', 'Message')
    from datetime import datetime
    today = datetime.now().strftime('%Y-%m-%d')
    Message.objects.update_or_create(defaults={'date': today})

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0078_remove_message_datemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_date),
    ]
