# Generated by Django 3.1.4 on 2023-12-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0079_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
