# Generated by Django 3.1.4 on 2023-12-30 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0080_remove_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 19, 22, 48, 220878)),
        ),
    ]
