# Generated by Django 3.1.4 on 2023-12-30 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0082_auto_20231230_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 19, 24, 11, 964730)),
        ),
    ]
