# Generated by Django 3.1.4 on 2024-01-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0083_auto_20231230_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
