# Generated by Django 3.1.4 on 2024-01-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0086_auto_20240120_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Country',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
