# Generated by Django 3.1.4 on 2024-01-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0087_auto_20240120_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
