# Generated by Django 3.1.4 on 2024-02-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0090_auto_20240120_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sex',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
