# Generated by Django 3.0.12 on 2024-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0092_formation_formation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap_id', models.IntegerField(default=0)),
                ('frmt_id', models.IntegerField(default=0)),
                ('titre', models.TextField(default='')),
                ('objectif', models.TextField(default='')),
                ('cours', models.TextField(default='')),
                ('cours_type', models.TextField(default='')),
                ('exo', models.TextField(default='')),
                ('exo_type', models.TextField(default='')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap_id', models.IntegerField(default=0)),
                ('frmt_id', models.IntegerField(default=0)),
                ('quizz_id', models.IntegerField(default=0)),
                ('question', models.TextField(default='')),
                ('qst_type', models.TextField(default='')),
                ('answer', models.TextField(default='')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bientot',
            name='prog_resume',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='profile_pic',
            field=models.CharField(default='default-pic.jpg', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
