# Generated by Django 3.0.12 on 2024-02-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0093_auto_20240217_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
