# Generated by Django 3.0.12 on 2024-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0094_auto_20240217_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='duree_min',
            field=models.CharField(default='Undefined', max_length=100),
        ),
    ]
