# Generated by Django 3.0.12 on 2024-02-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0095_chapitre_duree_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='objectif',
        ),
    ]
