# Generated by Django 3.0.12 on 2024-02-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0096_remove_chapitre_objectif'),
    ]

    operations = [
        migrations.CreateModel(
            name='ojectif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap_id', models.IntegerField(default=0)),
                ('frmt_id', models.IntegerField(default=0)),
                ('objctf_id', models.IntegerField(default=0)),
                ('objctf_content', models.TextField(default='')),
            ],
        ),
    ]
