# Generated by Django 3.0.12 on 2024-02-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0097_ojectif'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojectif',
            name='duree_min',
            field=models.CharField(default='Undefined', max_length=100),
        ),
    ]
