# Generated by Django 3.0.12 on 2024-02-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0098_ojectif_duree_min'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ojectif',
            new_name='objectif',
        ),
    ]
