# Generated by Django 3.0.12 on 2024-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0099_auto_20240217_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='description',
            field=models.TextField(default='Descripioin du chapitre <django.db.models.fields.IntegerField>'),
        ),
    ]
