# Generated by Django 3.0.12 on 2024-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0101_auto_20240217_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='demande_inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmd_id', models.IntegerField(default=0)),
                ('matricule_user', models.IntegerField(default=0)),
                ('formation_id', models.IntegerField(default=0)),
                ('status', models.CharField(default='waiting', max_length=100)),
                ('dmd_date', models.CharField(default='2024-02-24', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='formation_prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formation',
            name='formation_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
