# Generated by Django 3.0.12 on 2024-02-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0102_auto_20240224_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='foormation_img',
            new_name='formation_img',
        ),
    ]
