# Generated by Django 3.0.12 on 2024-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0104_formation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='formation_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
