# Generated by Django 3.0.12 on 2024-02-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0105_auto_20240224_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='frmt_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
