# Generated by Django 3.0.12 on 2024-02-24 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0106_auto_20240224_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='id',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='chap_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='description',
            field=models.TextField(default='Description du chapitre ...'),
        ),
    ]
