# Generated by Django 3.0.12 on 2024-02-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0107_auto_20240224_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='status',
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-02-29', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-02-29', max_length=100),
        ),
    ]
