# Generated by Django 3.0.12 on 2024-02-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0108_auto_20240229_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='cours',
            new_name='cours_content',
        ),
        migrations.RenameField(
            model_name='chapitre',
            old_name='cours_type',
            new_name='cours_file_type',
        ),
        migrations.RenameField(
            model_name='chapitre',
            old_name='exo',
            new_name='exemple_content',
        ),
        migrations.RenameField(
            model_name='chapitre',
            old_name='exo_type',
            new_name='exemple_file_type',
        ),
    ]
