# Generated by Django 3.0.12 on 2024-02-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0109_auto_20240229_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='cours_content',
            field=models.TextField(default='UNUPLOADED'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='cours_file_type',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='duree_min',
            field=models.CharField(default='UNDEFINED', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='exemple_content',
            field=models.TextField(default='UNUPLOADED'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='exemple_file_type',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='titre',
            field=models.TextField(default='UNDEFINED'),
        ),
    ]
