# Generated by Django 3.0.12 on 2024-03-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0111_chapitre_chap_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_progess',
            fields=[
                ('matricule', models.IntegerField(default=0)),
                ('chap_id', models.AutoField(primary_key=True, serialize=False)),
                ('frmt_id', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='WAITING', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-03-02', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-03-02', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='formation_img',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='frmt_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
