# Generated by Django 3.0.12 on 2024-03-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0112_auto_20240302_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectif',
            name='frmt_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
