# Generated by Django 3.0.12 on 2024-03-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0114_formation_formation_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande_inscription',
            name='id',
        ),
        migrations.AddField(
            model_name='demande_inscription',
            name='adress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='demande_inscription',
            name='already_signed_up',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='demande_inscription',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='demande_inscription',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='demande_inscription',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='demande_inscription',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='demande_inscription',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='demande_inscription',
            name='sex',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='demande_inscription',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-03-12', max_length=100),
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='formation_id',
            field=models.CharField(default='Unspecified', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-03-12', max_length=100),
        ),
    ]
