# Generated by Django 3.0.12 on 2024-03-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0116_auto_20240316_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='quizz_content',
            field=models.TextField(default='UNUPLOADED'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='quizz_file_type',
            field=models.TextField(default='UNKNOWN'),
        ),
    ]
