# Generated by Django 3.0.12 on 2024-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0117_auto_20240316_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='id',
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-03-30', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-03-30', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
