# Generated by Django 3.0.12 on 2024-03-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0118_auto_20240330_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
