# Generated by Django 3.0.12 on 2024-03-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0119_utilisateur_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='id',
        ),
    ]
