# Generated by Django 3.0.12 on 2024-03-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0121_utilisateur_date_souscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_inscription',
            name='date_validation',
            field=models.DateField(null=True, blank=True), 
        ),
    ]
