# Generated by Django 3.0.12 on 2024-03-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0124_demande_inscription_date_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='id',
        ),
        migrations.AlterField(
            model_name='formation',
            name='formation_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='souscription_formation',
            fields=[
                ('dmd_souscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(default='UNSPECIFIED', max_length=50)),
                ('ref_transact', models.CharField(default='UNSPECIFIED', max_length=100)),
                ('souscription_status', models.CharField(default='Waiting', max_length=50)),
                ('date_souscription', models.DateField(default='2024-03-30')),
                ('date_validation', models.CharField(default='', max_length=50)),
                ('formation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.formation')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.utilisateur')),
            ],
        ),
    ]
