# Generated by Django 3.0.12 on 2024-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0127_auto_20240406_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_inscription',
            name='formation_id',
            field=models.CharField(default='Unspecified', max_length=100),
        ),
    ]
