# Generated by Django 3.0.12 on 2024-04-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0130_auto_20240406_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='paiement',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_transact', models.CharField(max_length=100, unique=True)),
                ('sender', models.CharField(default='UNSPECIFIED', max_length=50)),
                ('receiver', models.CharField(default='UNSPECIFIED', max_length=50)),
                ('transact_type', models.CharField(default='UNSPECIFIED', max_length=50)),
                ('remarque', models.TextField(default='UNSPECIFIED', max_length=500)),
                ('formation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.formation')),
            ],
        ),
    ]
