# Generated by Django 3.0.12 on 2024-04-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0133_auto_20240406_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_paiemnet',
            field=models.DateField(default='2024-04-06'),
        ),
    ]
