# Generated by Django 3.0.12 on 2024-04-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0134_paiement_date_paiemnet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='date_paiemnet',
            new_name='date_paiement',
        ),
    ]
