# Generated by Django 3.0.12 on 2024-04-13 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0135_auto_20240406_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscription_formation',
            old_name='date_validation',
            new_name='date_modification',
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-04-13', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-04-13', max_length=100),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='souscription_formation',
            name='date_souscription',
            field=models.DateField(default='2024-04-13'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_souscription',
            field=models.DateField(default='2024-04-13'),
        ),
    ]
