# Generated by Django 3.0.12 on 2024-04-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0136_auto_20240413_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-04-20', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-04-20', max_length=100),
        ),
        migrations.AlterField(
            model_name='souscription_formation',
            name='date_souscription',
            field=models.DateField(default='2024-04-20'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_souscription',
            field=models.DateField(default='2024-04-20'),
        ),
        migrations.CreateModel(
            name='True_answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=500)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_possible',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=500)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Question')),
            ],
        ),
    ]
