# Generated by Django 3.0.12 on 2024-04-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0137_auto_20240420_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chap_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.chapitre'),
        ),
    ]
