# Generated by Django 3.0.12 on 2024-04-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0138_question_chap_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='formation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.formation'),
        ),
        migrations.AddField(
            model_name='true_answer',
            name='formation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.formation'),
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-04-27', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-04-27', max_length=100),
        ),
        migrations.AlterField(
            model_name='souscription_formation',
            name='date_souscription',
            field=models.DateField(default='2024-04-27'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_souscription',
            field=models.DateField(default='2024-04-27'),
        ),
    ]
