# Generated by Django 3.0.12 on 2024-04-27 10:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0139_auto_20240427_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='True_answer',
        ),
    ]
