# Generated by Django 3.0.12 on 2024-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0140_auto_20240427_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_possible',
            name='answer_alias',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='answer_possible',
            name='answer_text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
