# Generated by Django 3.0.12 on 2024-05-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0141_auto_20240427_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-05-04', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-05-04', max_length=100),
        ),
        migrations.AlterField(
            model_name='souscription_formation',
            name='date_souscription',
            field=models.DateField(default='2024-05-04'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_souscription',
            field=models.DateField(default='2024-05-04'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(default='', max_length=50)),
                ('chap_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.chapitre')),
                ('formation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.formation')),
                ('matricule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.utilisateur')),
            ],
        ),
    ]
