# Generated by Django 3.0.12 on 2024-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0142_auto_20240504_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.IntegerField(default='0'),
        ),
    ]
