# Generated by Django 3.0.12 on 2024-05-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0143_auto_20240504_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='activitys',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='organisation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='titre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-05-11', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-05-11', max_length=100),
        ),
        migrations.AlterField(
            model_name='souscription_formation',
            name='date_souscription',
            field=models.DateField(default='2024-05-11'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_souscription',
            field=models.DateField(default='2024-05-11'),
        ),
    ]
