# Generated by Django 3.0.12 on 2024-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0145_auto_20240525_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-06-01', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-06-01', max_length=100),
        ),
        migrations.AlterField(
            model_name='souscription_formation',
            name='date_souscription',
            field=models.DateField(default='2024-06-01'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_souscription',
            field=models.DateField(default='2024-06-01'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_pic',
            field=models.CharField(default='default-pic.jpg', max_length=500),
        ),
    ]
