# Generated by Django 3.0.12 on 2024-06-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0147_auto_20240615_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='formation_presentation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
