# Generated by Django 3.0.12 on 2024-06-22 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0148_formation_formation_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_chap',
            name='cours_content',
            field=models.TextField(default='UNUPLOADED'),
        ),
        migrations.AddField(
            model_name='video_chap',
            name='cours_file_type',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='video_chap',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video_chap',
            name='description',
            field=models.TextField(default='Description du chapitre ...'),
        ),
        migrations.AddField(
            model_name='video_chap',
            name='duree_min',
            field=models.CharField(default='UNDEFINED', max_length=100),
        ),
        migrations.AddField(
            model_name='video_chap',
            name='exemple_content',
            field=models.TextField(default='UNUPLOADED'),
        ),
        migrations.AddField(
            model_name='video_chap',
            name='exemple_file_type',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='video_chap',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video_chap',
            name='titre',
            field=models.TextField(default='UNDEFINED'),
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-06-22', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-06-22', max_length=100),
        ),
        migrations.AlterField(
            model_name='souscription_formation',
            name='date_souscription',
            field=models.DateField(default='2024-06-22'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_souscription',
            field=models.DateField(default='2024-06-22'),
        ),
    ]
