# Generated by Django 3.0.12 on 2024-06-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0149_auto_20240622_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_chap',
            name='cours_file_type',
        ),
        migrations.RemoveField(
            model_name='video_chap',
            name='exemple_file_type',
        ),
        migrations.RemoveField(
            model_name='video_chap',
            name='video_path',
        ),
    ]
