# Generated by Django 3.0.12 on 2024-07-06 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0150_auto_20240622_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('atelier_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_debut', models.DateTimeField(default=None)),
                ('date_fin', models.DateTimeField(default=None)),
                ('img', models.TextField(default='UNUPLOADED')),
                ('description', models.TextField(default='UNUPLOADED')),
            ],
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-07-06', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-07-06', max_length=100),
        ),
        migrations.AlterField(
            model_name='souscription_formation',
            name='date_souscription',
            field=models.DateField(default='2024-07-06'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_souscription',
            field=models.DateField(default='2024-07-06'),
        ),
    ]
