# Generated by Django 3.0.12 on 2024-07-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0153_auto_20240706_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='heure_debut',
            field=models.CharField(default='8', max_length=20),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='heure_fin',
            field=models.CharField(default='17', max_length=20),
        ),
    ]
