# Generated by Django 3.0.12 on 2024-07-06 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0154_auto_20240706_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='date_debut',
            field=models.DateField(default=None),
        ),
    ]
