# Generated by Django 3.0.12 on 2024-07-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0155_auto_20240706_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='date_fin',
            field=models.DateField(default=None),
        ),
    ]
