# Generated by Django 3.0.12 on 2024-08-03 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0156_auto_20240706_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='nb_place',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='type',
            field=models.CharField(default='UNDEFINED', max_length=200),
        ),
        migrations.AlterField(
            model_name='demande_inscription',
            name='dmd_date',
            field=models.CharField(default='2024-08-03', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default='2024-08-03', max_length=100),
        ),
        migrations.AlterField(
            model_name='souscription_formation',
            name='date_souscription',
            field=models.DateField(default='2024-08-03'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_souscription',
            field=models.DateField(default='2024-08-03'),
        ),
        migrations.CreateModel(
            name='Souscription_atelier',
            fields=[
                ('souscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
                ('atelier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Atelier')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.utilisateur')),
            ],
        ),
    ]
