# Generated by Django 3.0.12 on 2024-08-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0157_auto_20240803_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='souscription_atelier',
            unique_together={('matricule', 'atelier_id')},
        ),
    ]
